export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const MESSAGE_FAILED = "MESSAGE_FAILED";
export const RESET_LOGIN = "RESET_LOGIN";
